#!/bin/sh
## warning! just like gfetch, this thing contains
## fuck loads of stolen code!

# suppress errors
exec 2>/dev/null

os=$(. /etc/os-release && echo ${NAME})

arch=$(uname -m)

uptime=$(uptime | sed -E 's/^[^,]*up *//; s/, *[[:digit:]]* users?.*//; s/min/minutes/; s/([[:digit:]]+):0?([[:digit:]]+)/\1 hours, \2 minutes/')

ram=$(free -m | awk 'NR==2{printf "%s/%s MiB", $3, $2}')

cpu=$(grep "model name" /proc/cpuinfo | head -1 | cut -d ':' -f2)

# display resolution
dimensions=$(xdpyinfo | grep dimensions: | awk '{print $2}')
width=$(echo $dimensions | sed 's/x.*//')
height=$(echo $dimensions | sed 's/.*x//')

## this should improve how the output looks if xdpyinfo returns an error
## is held up by hopes and dreams
xdpyinfo > /dev/null 2>&1 &&
	resolution=$(printf "$width x $height")

# root partition's filesystem
fs=$(df -T ~ | awk 'NR==2 {printf $2}')

# root partition's used space
disk=$(df -h ~ | awk 'NR==2 {print $1":", $3}' | sed 's/\/dev\///')

hostname=$(cat /etc/hostname)

# the output
cat <<EOF
		$USER@$hostname
    (\(\	-----------
   j". ..	os: $os $arch
   (  . .)	shell: $SHELL
   |   ° ¡	uptime: $uptime
   ¿     ;	ram: $ram
   c?".UJ	cpu:$cpu
		resolution: $resolution
		fs: $fs
		$disk
EOF
