#!/bin/sh
## warning! just like gfetch, this thing contains
## fuck loads of stolen code!

# fetch the OS name
os=$(. /etc/os-release && echo ${NAME})

# fetch the os arch
arch=$(uname -m)

# fetch the uptime, a bit of nonsense though ( . .)
uptime=$(uptime | sed -E 's/^[^,]*up *//; s/, *[[:digit:]]* users?.*//; s/min/minutes/; s/([[:digit:]]+):0?([[:digit:]]+)/\1 hours, \2 minutes/')

# fetch the memory usage
ram=$(free -m | awk 'NR==2{printf "%sMB", $3, $2}')

# fetch the cpu model
cpu=$(grep "model name" /proc/cpuinfo | head -1 | cut -d ':' -f2)

# fetch the display resolution
res=$(xdpyinfo | grep dimensions: | awk '{print $2}')

# fetch the root partition disk space
disk=$(df -h | grep -w "/" | awk '{print $1":", $3}')

cat <<EOF
		$USER@$HOSTNAME
    (\(\	-----------
   j". ..	os: $os $arch
   (  . .)	shell: $SHELL
   |   ° ¡	uptime: $uptime
   ¿     ;	ram: $ram
   c?".UJ	cpu:$cpu
		resolution: $res
		$disk
EOF
