#!/bin/sh
## warning! just like gfetch, this thing contains
## fuck loads of stolen code!

# fetch the OS name
os=$(. /etc/os-release && echo ${NAME})

# fetch the os arch
arch=$(uname -m)

# fetch the uptime
uptime=$(uptime | sed -E 's/^[^,]*up *//; s/, *[[:digit:]]* users?.*//; s/min/minutes/; s/([[:digit:]]+):0?([[:digit:]]+)/\1 hours, \2 minutes/')

# fetch the memory usage
ram=$(free --mega | awk 'NR==2{printf "%s/%sMB", $3, $2}')

# fetch the cpu model
cpu=$(grep "model name" /proc/cpuinfo | head -1 | cut -d ':' -f2)

# fetch the display resolution
resolution=$(xdpyinfo | grep dimensions: | awk '{print $2}')
width=$(echo $resolution | sed 's/x.*//')
height=$(echo $resolution | sed 's/.*x//')

# fetch the root partition filesystem
fs=$(df -T | grep -w "/" | awk '{printf $2}')

# fetch the root partition used space
disk=$(df -h | grep -w "/" | awk '{print $1":", $3}' | sed 's/\/dev\///')

# fetch the hostname
hostname=$(cat /etc/hostname)

cat <<EOF
		$USER@$hostname
    (\(\	-----------
   j". ..	os: $os $arch
   (  . .)	shell: $SHELL
   |   ° ¡	uptime: $uptime
   ¿     ;	ram: $ram
   c?".UJ	cpu:$cpu
		resolution: $width x $height
		fs: $fs
		$disk
EOF
